Edit site informations
adshares/adpanel pull request #890
Opened 2022-05-13 14:45 UTC by Niko-Yea

2022-05-16 08:40 UTC, PawelPodkalicki requested changes

2022-05-16 08:40 UTC, PawelPodkalicki commented on src/app/publisher/site-details/site-details.component.ts
> +    this.siteLinkUrl = this.site.medium === 'metaverse'
Check if vendor is decentraland

2022-05-19 11:30 UTC, m-pilarczyk approved these changes

2022-05-19 11:31 UTC, PawelPodkalicki approved these changes

2022-05-19 11:32 UTC, merged