link to wiki how to add an html ad
adshares/adpanel pull request #899
Opened 2022-05-26 16:01 UTC by szych111

link to how to add an html ad

2022-05-26 16:44 UTC, PawelPodkalicki approved these changes

2022-05-30 07:31 UTC, m-pilarczyk requested changes

2022-05-30 07:31 UTC, m-pilarczyk commented on src/app/models/enum/link.enum.ts
> +export const WIKI_HTML_AD = 'https://github.com/adshares/adserver/wiki/How-to-add-html-banner'
```suggestion
export const WIKI_HTML_AD = 'https://adshar.es/howtohtmlbanner'
```

2022-05-30 07:31 UTC, m-pilarczyk commented on src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.ts
> +
```suggestion
```

2022-05-31 10:37 UTC, m-pilarczyk approved these changes

2022-06-01 14:25 UTC, merged