[WIP] Handle backend taxonomy changes
adshares/adpanel pull request #918
Opened 2022-07-08 08:41 UTC by PawelPodkalicki

2022-07-13 17:01 UTC, m-pilarczyk requested changes

2022-07-13 17:01 UTC, m-pilarczyk commented on src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.ts
> +    console.log('adUnitsValid', adUnitsValid)
Remove debug code

2022-07-14 08:52 UTC, PawelPodkalicki commented on src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.ts
> +    console.log('adUnitsValid', adUnitsValid)
Removed

2022-07-14 16:56 UTC, m-pilarczyk approved these changes

2022-07-14 16:56 UTC, merged